pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
spring:
  datasource:
    url: jdbc:mysql://111.229.178.51:3306/market?serverTimezone=UTC
    username: root
    password: FUCjuP#H4;dm
    driver-class-name: com.mysql.cj.jdbc.Driver
